name: SpeedLimiter
version: @version@
main: fi.fabianadrian.speedlimiter.SpeedLimiter
api-version: 1.16
authors: [ FabianAdrian ]
permissions:
  speedlimiter.bypass:
    description: Bypass limits.
  speedlimiter.admin:
    description: Access /speedlimiter command.
commands:
  speedlimiter:
    permission: speedlimiter.admin
